### ISSUE TITLE
Do we need the `dev_requirements` directory?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-cg#7]
I've forgotten why it exists again. Travis works just fine with dependencies in setup.py

@jonc125 ?

**Comment by jonc125** [comment]
It's to enable developers of the module to ensure they're all using the same versions of dependencies, so you get consistent behaviour for each dev. Travis then testing with later versions is fine, as that tests the end user experience. Since Travis will install packages from fresh every test run, but devs will only reinstall if they notice a problem so can easily get out of sync.

**Comment by jonc125** [comment]
See also #9!
