### ISSUE TITLE
Update jinja version

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-cg#9]
Or maybe stop pinning altogether @jonc125 ? I'm really not seeing any benefits to this approach!

- requires extra tooling, more files, more infrastructure stuff to learn
- triggers security warnings, possibly makes server install less safe
- stops developers from detecting incompatibilities

**Comment by jonc125** [comment]
Pinning is important for ensuring smooth deployments to production systems. It means that:
- all developers have the same dependency versions, so you don't have "works for me" type bugs happening (as much)
- you can test that everything works with a known set of versions
- you can deploy this set of known working versions to the live server. In particular, this prevents the server's behaviour randomly changing just because of when you did the deployment, and you can test more robustly that a deployment will work before you do it (e.g. by deploying to a staging server)
- you can have separate automated tests that things still work with the 'latest' versions that a user might install, so still detect incompatibilities
- security warnings are good, as they alert you to redeploy on the server. Otherwise you could have a security hole live on the server for months without realising, during quiet dev periods.

**Comment by MichaelClerx** [comment]
The first two are limitations, in my view:

- all developers have the same dependency versions, so you don't have "works for me" type bugs happening (as much)
- you can test that everything works with a known set of versions

Those works-for-me bugs are good things to find!

I like point 3, but it applies only to projects where you have everything running on a dedicated server. That might be true for web lab at the moment, but really shouldn't be in the long run

Point 5 is cool

**Comment by MichaelClerx** [comment]
Closing this, as the issue is fixed

**Comment by jonc125** [comment]
For the library repos we could perhaps combine both viewpoints by making the main requirements .in files look like
```
--index-url https://pypi.python.org/simple/

-e https://github.com/ModellingWeblab/cellmlmanip.git#egg=cellmlmanip
-e .
```
(idea from https://caremad.io/posts/2013/07/setup-vs-requirement/)
and use pip-tools to generate the pinned .txt versions.

**Comment by MichaelClerx** [comment]
I've tried like this:

```
-e git://github.com/ModellingWebLab/cellmlmanip.git#egg=cellmlmanip
-e ..
```

But that adds the dependency

```
-e file:///home/michael/dev/weblab/weblab_cg
```
in the `.txt` file

**Comment by MichaelClerx** [comment]
By the way, that article seems to say pinning is for applications, setting minimal versions is for libraries. I agree 100%. But cellmlmanip and weblab_cg are libraries!

**Comment by jonc125** [comment]
They are, which is why using setup.py is good for users. But they will also be crucial components in the Web Lab application, which will require testing with known dependency versions. And so it's convenient for us if those versions are specified with the libraries, rather than separately (as you'd then need extra repos, or perhaps in deployment, storing the pinned versions, which could more easily get out of sync with the libraries, and testing is more awkward).
